backend:
  repo_path: ../golang-example
  req_template_path: Templates/Software Requirements Specification - Backend.docx
  req_output_name: "Software Requirements Specification - Backend.docx"
  ver_template_path: Templates/Verification Protocol - Backend.docx
  ver_output_name: "Verification Protocol - Backend.docx"
  tag: API
  language: golang
  sections:
    - display_name: "Users Endpoint"
      filenames:
        - "golang_example_test.go"
  ignore:
mobile:
  repo_path: ../swift-example
  req_template_path: Templates/Software Requirements Specification - iOS App.docx
  req_output_name: "Software Requirements Specification - iOS App.docx"
  ver_template_path: Templates/Verification Protocol - iOS App.docx
  ver_output_name: "Verification Protocol - iOS App.docx"
  tag: IOS
  language: swift
  sections:
    - display_name: "Login Screen"
      filenames:
        - "LoginViewTests.swift"
