backend:
  repo_path: ../golang-example
  repo_test_path: ../golang-example/tests
  req_template_path: Templates/Software Requirements Specification - Backend.docx
  req_output_name: "Software Requirements Specification - Backend"
  ver_template_path: Templates/Verification Protocol - Backend.docx
  ver_output_name: "Verification Protocol - Backend"
  tag: API
  language: golang
  sections:
    - display_name: "Users Endpoint"
      filename: "golang_example_test.go"
  ignore:
mobile:
  repo_path: ../swift-example
  repo_test_path: ../swift-example/Tests
  req_template_path: Templates/Software Requirements Specification - iOS App.docx
  req_output_name: "Software Requirements Specification - iOS App"
  ver_template_path: Templates/Verification Protocol - iOS App.docx
  ver_output_name: "Verification Protocol - iOS App"
  tag: IOS
  language: swift
  sections:
    - display_name: "Login Screen"
      filename: "LoginViewTests.swift"
